version: "3.8"

services:
  app:
    build: .
    container_name: transformers-firefunction_v1
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      - .:/app
    command: ["python", "main.py"]
